apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-waf
  namespace: nginx-ingress
data:
  waf-policy.json: |
    {
    "name": "nginx-policy",
    "template": { "name": "POLICY_TEMPLATE_NGINX_BASE" },
    "applicationLanguage": "utf-8",
    "enforcementMode": "blocking"
    }
